[build]
rustflags = ["-D", "warnings"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,@executable_path/../Frameworks,-rpath,/Applications/VLC.app/Contents/MacOS/lib"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,@executable_path/../Frameworks,-rpath,/Applications/VLC.app/Contents/MacOS/lib"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-args=/SUBSYSTEM:WINDOWS"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,$ORIGIN"]
